services:
  # api:
  #   build: .
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - POSTGRESQL_HOST=${POSTGRESQL_HOST}
  #     - POSTGRESQL_PORT_NUMBER=${POSTGRESQL_PORT_NUMBER}
  #     - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
  #     - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
  #     - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
  #   depends_on:
  #     database:
  #       condition: service_healthy
  #   volumes:
  #     - .:/app
  #   command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  database:
    image: postgres:13
    container_name: database

    environment:
      - POSTGRES_USER=monitoring
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=monitoring
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U monitoring -d monitoring"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
